//Get all appointments
GET http://localhost:8000/api/appointment/

###
//Get all appointments
GET http://localhost:8000/api/appointment/archive/all

###
//
GET http://localhost:8000/api/appointment/670cb10dfea64abddaf30c95

###
//create appointment
POST http://localhost:8000/api/appointment/create HTTP/1.1
Content-Type: application/json

{
    "appointment_type":"6700ad79f67ac13cffcdab28",
    "patient_id":"67016f6829b8c6514547915c",
    "doctor_id":"66ffd2b755f261b89f676fea",
    "date":"2024-09-20T15:00:00Z",
    "phone":"091234353",
    "time":"6703c1423cf17d6d0767c9fe"
}

###
//update
PATCH  http://localhost:8000/api/appointment/update/670cb10dfea64abddaf30c95 HTTP/1.1
Content-Type: application/json

{
    "doctor_id":"670dfbde6a8faaf712530ce3",
    "time":"6703c7ed5648674e55b87561",
}
###
//archive appointment
PATCH  http://localhost:8000/api/appointment/archive/save/670cb10dfea64abddaf30c95
Content-Type: application/json

{
    "isArchive":true
}
###
//delete appointment
DELETE http://localhost:8000/api/appointment/670cc2627cd6defa2ac85985



#####################################################################################################
//Appointment type ______________________________________________________________________________________

//get
GET http://localhost:8000/api/appointment/types/all

###
//archive
GET http://localhost:8000/api/appointment/types/archive/all

###
//get one
GET http://localhost:8000/api/appointment/type/6700ad79f67ac13cffcdab28

###
//create type
POST http://localhost:8000/api/appointment/type/create HTTP/1.1
Content-Type: application/json

{
    "name":"TestType2"
}

###
//update type
PATCH  http://localhost:8000/api/appointment/type/update/6700b83c95e996c40e437172
Content-Type: application/json

{
    "name":"update type"
}
###
//archvie type
PATCH  http://localhost:8000/api/appointment/type/archive/save/6700ad79f67ac13cffcdab28
Content-Type: application/json

{
    "isArchive":true
}

###
//delete
DELETE http://localhost:8000/api/appointment/type/delete/6700ad79f67ac13cffcdab28 



##########################################################################################################
//Appointment time ______________________________________________________________________________________

GET http://localhost:8000/api/appointment/time/all

###

GET http://localhost:8000/api/appointment/time/archive/all

###
// get one time
GET http://localhost:8000/api/appointment/time/6703c7ed5648674e55b87561

###

// create
POST http://localhost:8000/api/appointment/time/create 
Content-Type:  application/json

{
    "time" : "4:00"
}
###
//update
PATCH http://localhost:8000/api/appointment/time/update/6703c1423cf17d6d0767c9fe
Content-Type: application/json

{
    "time":"TestTime"
}
###
//archvie save
PATCH http://localhost:8000/api/appointment/time/archive/save/67148ae3efe0a56c11cfc5a5
Content-Type: application/json

{
    "isArchive":false
}
###
//delete
DELETE http://localhost:8000/api/appointment/time/delete/6715d1085e595561a34054f2 HTTP/1.1

##############################################################################################