//Get all appointments
GET http://localhost:8000/api/appointment/

###
//
GET http://localhost:8000/api/appointment/6703c4b6c21d4bbf903a20b9

###
//create appointment
POST http://localhost:8000/api/appointment/create HTTP/1.1
Content-Type: application/json

{
    "appointment_type":"6700ad79f67ac13cffcdab28",
    "patient_id":"67016f6829b8c6514547915c",
    "doctor_id":"66ffd2b755f261b89f676fea",
    "date":"2024-09-20T15:00:00Z",
    "status":false,
    "time":"6703c1423cf17d6d0767c9fe"
}

###
//update
PATCH  http://localhost:8000/api/appointment/update/6703c4b6c21d4bbf903a20b9 HTTP/1.1
Content-Type: application/json

{
    "appointment_type":"6700ad79f67ac13cffcdab28",
    "time":"6703c1423cf17d6d0767c9fe",
    "isArchive":false
}

###
//delete appointment
DELETE http://localhost:8000/api/appointment/6703c4b6c21d4bbf903a20b9

###
//Appointment type ______________________________________________________________________________________

//get
GET http://localhost:8000/api/appointment/types/all

###


//get one
GET http://localhost:8000/api/appointment/type/6700ad79f67ac13cffcdab28

###
//create type
POST http://localhost:8000/api/appointment/type/create HTTP/1.1
Content-Type: application/json
{
    "name":"TestType"
}

###
//update type
PATCH  http://localhost:8000/api/appointment/type/update/6700b83c95e996c40e437172
Content-Type: application/json

{
    "name":"update type"
}


###
//delete
DELETE http://localhost:8000/api/appointment/type/delete/6700b3b2999d124f090c0469 

###
//Appointment time ______________________________________________________________________________________

GET http://localhost:8000/api/appointment/time/all

###

// get one time
GET http://localhost:8000/api/appointment/time/6703c7ed5648674e55b87561

###

// create
POST http://localhost:8000/api/appointment/time/create 
Content-Type:  application/json

{
    "time" : "4:30"
}
###
//update
PATCH http://localhost:8000/api/appointment/time/update/6703c1423cf17d6d0767c9fe
Content-Type: application/json

{
    "time":"TestTime"
}
###
//delete
DELETE http://localhost:8000/api/appointment/time/delete/6703c1423cf17d6d0767c9fe HTTP/1.1