//get all doctors
GET http://localhost:8000/api/doctors

###
//create doctor
POST http://localhost:8000/api/doctors/register
Content-Type: application/json
{
    "name":"yaco",
    "email": "doctor@gmail.com",
    "phone":"09234542",
    "specialty":"66ef8bb0b7bd10855c3408d6"
}

###
//delete doctor
DELETE http://localhost:8000/api/doctors/{doctor_id}
