###
//get all patients
GET http://localhost:8000/api/patients/

//get one patient
GET http://localhost:8000/api/patients/{patientID}

###
//create patient
POST http://localhost:8000/api/patients/register HTTP/1.1
Content-Type: application/json
{
    "name": "yaco",
    "email": "yaco@gmail.com",
    "phone": 1234,
    "password": "yaco"
}

###
//login patient
POST http://localhost:8000/api/patients/login HTTP/1.1
Content-Type: application/json
{
    "email": "yaco@gmail.com",
    "password": "yaco"
}

###
//update patient
//get all patients
PATCH http://localhost:8000/api/patients/{patientIDs}

###
//delete patient
DELETE http://localhost:8000/api/patients HTTP/1.1