//get all specialties
GET http://localhost:8000/api/specialties/

###
//create specialty
POST http://localhost:8000/api/specialties/create HTTP/1.1
Content-Type: application/json

{
    "name":"Surgery"
}

###
//delete specialty
DELETE http://localhost:8000/api/specialties/{id} HTTP/1.1