//get all specialties
GET http://localhost:8000/api/specialties/

###
//get all archive
GET http://localhost:8000/api/specialties/archive/all

###
//get one
GET http://localhost:8000/api/specialties/670dfaae257a7badc12e696f

###
//create specialty
POST http://localhost:8000/api/specialties/create HTTP/1.1
Content-Type: application/json

{ 
    "name":"Test2"
}
###
//update 
PATCH  http://localhost:8000/api/specialties/update/6715f69afb6c5824c28c493b
Content-Type: application/json

{
    "name":"Test3"
}
###
//archive save 
PATCH  http://localhost:8000/api/specialties/archive/save/670dfaae257a7badc12e696f
Content-Type: application/json

{
    "isArchive":true
}
###
//delete specialty
DELETE http://localhost:8000/api/specialties/670dfaae257a7badc12e696f HTTP/1.1